FROM registry.access.redhat.com/ubi9/openjdk-21-runtime

LABEL owner="UWV"
LABEL team="CompetentNL"

USER root

COPY uwv-ca.pem /etc/pki/ca-trust/source/anchors/
COPY uwv-mcpaas-ap.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

# Harden the environment by removing unnecessary packages
RUN mkdir /application && \
    rpm -e --nodeps $(rpm -qa '*rpm*' '*dnf*' '*libsolv*' '*hawkey*' '*yum*' '*python*') && \
    chgrp -R 0 /application && \
    chmod -R g=u /application

# Switch to the non-root user
USER 185

ENV TZ="Europe/Amsterdam"