name: Release application

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 5'  # This runs the pipeline every Friday at 00:00
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '21', '25' ]

    steps:
      - uses: actions/checkout@v4

      - name: Repo name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}
          tags: |
            type=raw,value=${{ matrix.java-version }}
            type=raw,value=latest,enable=${{ matrix.java-version == '21' }}
            type=raw,value=java${{ matrix.java-version }}-latest
            type=raw,value=java${{ matrix.java-version }}-{{date 'YYYYMMDD-HHmm'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-java${{ matrix.java-version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
